### PR TITLE
Adding more descriptive options

### PR DESCRIPTION
**Pull request by ImkoMarijnissen**
When running `pumpkin-cli --help`, the options are not necessarily clear; and (what is more bothersome), it is not clear from the output what the possible values are for the different options.

This PR aims to address this by adding more descriptive documentation for the different options in combination with clarifying what the possible values are for the different options. All of the documentation now uses the `verbatim_doc_comment` so that it is in line with the rest of our documentation (and more importantly, that clap doesn't perform any weird line-breaking).

### CODE REVIEW

**Comment by ImkoMarijnissen** [comment]
@EmirDe Would it be possible for you to check the links I added to the papers for the different options? I did a best-effort search for what was mentioned but I cannot be entirely sure if everything is correct unfortunately

**Comment by maartenflippo** [comment]
I also removed the `CliArg` type in this PR. We used to have it because formatting was not configured on the underlying types, however, now that is the case so it can be removed.

**Review by maartenflippo — CHANGES_REQUESTED** [review]
Since this is about the presentation of `--help`, it would be nice to fill in the `author`, `version` and `about` fields in the `#[command(...)]` macro.

**Comment by ImkoMarijnissen** [comment]
> Since this is about the presentation of `--help`, it would be nice to fill in the `author`, `version` and `about` fields in the `#[command(...)]` macro.

I have added this information to the crate-level information (which should be the default that clap uses); please let me know if this is what you had in mind!

**Review by maartenflippo — APPROVED** [review]

**Pull request merged**
